# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sridhar1030
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: rekognition
# "service" is the name of this project. This will also be added to your AWS resource names.
service: backend

provider:
  name: aws
  runtime: nodejs20.x
  # region: ap-south-1  # Specify the AWS region here
  environment:
    BUCKET_NAME: backend-public-photos-dev-default
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "arn:aws:s3:::backend-public-photos-dev-default"
        - Effect: "Allow"
          Action:
            - "rekognition:detectLabels"
          Resource: "*"
functions:
  hello:
    handler: handler.savePhoto
    events:
      - httpApi:
          path: /
          method: post
  helloWorld:
    handler: handler.helloWorld
    events:
      - httpApi:
          path: /hello
          method: get

resources:
  Resources:
    PhotoBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-public-photos-${sls:stage}-${opt:uniqueSuffix, 'default'}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false

    PhotoBucketAllowPublicReadPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref PhotoBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "s3:GetObject"
              Resource:
                - !Join ['/', [!GetAtt PhotoBucket.Arn, '*']]
              Principal: "*"
            - Effect: Allow
              Action:
                - "s3:PutObject"
              Resource:
                - !Join ['/', [!GetAtt PhotoBucket.Arn, '*']]
              Principal: "*"



plugins:
  - serverless-offline

